% GMAT Script: MRO Visualization using SPICE
% Generated: 2025-03-27

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft MRO;
GMAT MRO.DateFormat = TAIModJulian;
GMAT MRO.Epoch = '23805.41988251';
GMAT MRO.CoordinateSystem = EarthMJ2000Eq;
GMAT MRO.DisplayStateType = Keplerian;
GMAT MRO.SMA = 7191.93881762902;
GMAT MRO.ECC = 0.02454974900598161;
GMAT MRO.INC = 12.85008005658097;
GMAT MRO.RAAN = 306.6148021947984;
GMAT MRO.AOP = 314.1905515359928;
GMAT MRO.TA = 99.88774933204814;
GMAT MRO.DryMass = 850;
GMAT MRO.Cd = 2.2;
GMAT MRO.Cr = 1.8;
GMAT MRO.DragArea = 15;
GMAT MRO.SRPArea = 1;
GMAT MRO.SPADDragScaleFactor = 1;
GMAT MRO.SPADSRPScaleFactor = 1;
GMAT MRO.AtmosDensityScaleFactor = 1;
GMAT MRO.ExtendedMassPropertiesModel = 'None';
GMAT MRO.NAIFId = -74;
GMAT MRO.NAIFIdReferenceFrame = -74900;
GMAT MRO.OrbitSpiceKernelName = {'C:\SPICE\MRO\mro_ab.bsp'};
GMAT MRO.SCClockSpiceKernelName = {'C:/SPICE/MRO/MRO_SCLKSCET.00113.tsc'};
GMAT MRO.FrameSpiceKernelName = {'C:/SPICE/MRO/mro_v16.tf'};
GMAT MRO.OrbitColor = [73 107 245];
GMAT MRO.TargetColor = Teal;
GMAT MRO.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT MRO.CdSigma = 1e+70;
GMAT MRO.CrSigma = 1e+70;
GMAT MRO.Id = 'SatId';
GMAT MRO.Attitude = CoordinateSystemFixed;
GMAT MRO.SPADSRPInterpolationMethod = Bilinear;
GMAT MRO.SPADSRPScaleFactorSigma = 1e+70;
GMAT MRO.SPADDragInterpolationMethod = Bilinear;
GMAT MRO.SPADDragScaleFactorSigma = 1e+70;
GMAT MRO.AtmosDensityScaleFactorSigma = 1e+70;
GMAT MRO.ModelFile = 'C:\Users\merte\Desktop\Italy\PoliMi\PoliSpace\GMAT\data\vehicle\models\mro.3ds';
GMAT MRO.ModelOffsetX = 0;
GMAT MRO.ModelOffsetY = 0;
GMAT MRO.ModelOffsetZ = 0;
GMAT MRO.ModelRotationX = 0;
GMAT MRO.ModelRotationY = 0;
GMAT MRO.ModelRotationZ = 0;
GMAT MRO.ModelScale = 1.9;
GMAT MRO.AttitudeDisplayStateType = 'Quaternion';
GMAT MRO.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT MRO.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT MRO.EulerAngleSequence = '321';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator spkProp;
GMAT spkProp.Type = SPK;
GMAT spkProp.StepSize = 100;
GMAT spkProp.CentralBody = Earth;
GMAT spkProp.EpochFormat = 'TAIModJulian';
GMAT spkProp.StartEpoch = '23805.41988251';

%----------------------------------------
%---------- Coordinate Systems
%----------------------------------------

Create CoordinateSystem MarsMJ2000Eq;
GMAT MarsMJ2000Eq.Origin = Mars;
GMAT MarsMJ2000Eq.Axes = MJ2000Eq;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView MROOrbitView;
GMAT MROOrbitView.SolverIterations = Current;
GMAT MROOrbitView.UpperLeft = [ 0 0 ];
GMAT MROOrbitView.Size = [ 0.8 0.8497474747474747 ];
GMAT MROOrbitView.RelativeZOrder = 680;
GMAT MROOrbitView.Maximized = false;
GMAT MROOrbitView.Add = {MRO, Mars};
GMAT MROOrbitView.CoordinateSystem = MarsMJ2000Eq;
GMAT MROOrbitView.DrawObject = [ true true ];
GMAT MROOrbitView.DataCollectFrequency = 1;
GMAT MROOrbitView.UpdatePlotFrequency = 50;
GMAT MROOrbitView.NumPointsToRedraw = 0;
GMAT MROOrbitView.ShowPlot = true;
GMAT MROOrbitView.MaxPlotPoints = 20000;
GMAT MROOrbitView.ShowLabels = true;
GMAT MROOrbitView.ViewPointReference = Mars;
GMAT MROOrbitView.ViewPointVector = [ 15528.68341064453 -10312.5699694008 -6051.2031445503 ];
GMAT MROOrbitView.ViewDirection = Mars;
GMAT MROOrbitView.ViewScaleFactor = 1.5;
GMAT MROOrbitView.ViewUpCoordinateSystem = MarsMJ2000Eq;
GMAT MROOrbitView.ViewUpAxis = Z;
GMAT MROOrbitView.EclipticPlane = Off;
GMAT MROOrbitView.XYPlane = On;
GMAT MROOrbitView.WireFrame = Off;
GMAT MROOrbitView.Axes = On;
GMAT MROOrbitView.Grid = Off;
GMAT MROOrbitView.SunLine = Off;
GMAT MROOrbitView.UseInitialView = On;
GMAT MROOrbitView.StarCount = 7000;
GMAT MROOrbitView.EnableStars = On;
GMAT MROOrbitView.EnableConstellations = On;

Create ReportFile ReportFile1;
GMAT ReportFile1.SolverIterations = Current;
GMAT ReportFile1.UpperLeft = [ 0.01764705882352941 0.04285714285714286 ];
GMAT ReportFile1.Size = [ 0.7852941176470588 0.7952380952380952 ];
GMAT ReportFile1.RelativeZOrder = 143;
GMAT ReportFile1.Maximized = false;
GMAT ReportFile1.Filename = 'ReportFile1.txt';
GMAT ReportFile1.Precision = 16;
GMAT ReportFile1.Add = {MRO.A1ModJulian, MRO.MarsMJ2000Eq.AOP, MRO.Mars.ECC, MRO.MarsMJ2000Eq.INC, MRO.MarsMJ2000Eq.RAAN, MRO.Mars.SMA, MRO.Mars.TA};
GMAT ReportFile1.WriteHeaders = true;
GMAT ReportFile1.LeftJustify = On;
GMAT ReportFile1.ZeroFill = Off;
GMAT ReportFile1.FixedWidth = true;
GMAT ReportFile1.Delimiter = ' ';
GMAT ReportFile1.ColumnWidth = 23;
GMAT ReportFile1.WriteReport = true;

Create GroundTrackPlot GroundTrackPlot1;
GMAT GroundTrackPlot1.SolverIterations = Current;
GMAT GroundTrackPlot1.UpperLeft = [ 0.1282352941176471 0.07323232323232323 ];
GMAT GroundTrackPlot1.Size = [ 0.7976470588235294 0.8522727272727273 ];
GMAT GroundTrackPlot1.RelativeZOrder = 678;
GMAT GroundTrackPlot1.Maximized = false;
GMAT GroundTrackPlot1.Add = {MRO, Earth};
GMAT GroundTrackPlot1.DataCollectFrequency = 1;
GMAT GroundTrackPlot1.UpdatePlotFrequency = 50;
GMAT GroundTrackPlot1.NumPointsToRedraw = 0;
GMAT GroundTrackPlot1.ShowPlot = true;
GMAT GroundTrackPlot1.MaxPlotPoints = 20000;
GMAT GroundTrackPlot1.CentralBody = Mars;
GMAT GroundTrackPlot1.TextureMap = 'Mars_JPLCaltechUSGS.jpg';

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate spkProp(MRO) {MRO.ElapsedDays = 185.3609};


